<img style="float: left;;" src='../Figures/iteso.jpg' width="50" height="100"/></a>

# <center> <font color= #000047> Repaso de la Librería NumPy</font> </center>


# Operaciones con NumPy

## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr_2 = arr + arr
arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
#Operacion con matrices
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
M.dot(M) # MxM

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [8]:
M**2 # MxM != M2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [9]:
M.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
M2 = np.arange(2,11).reshape(3,3)
M2


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [13]:
M@M2

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [20]:
a2 = np.array([[1,2,4],
          [2,2, 4]])

In [21]:
a2.shape, M.shape

((2, 3), (3, 3))

In [22]:
a2.dot(M) # a2xM != Mxa2

array([[37, 44, 51],
       [38, 46, 54]])

In [23]:
M.shape, a2.shape 

((3, 3), (2, 3))

In [24]:
M.dot(a2)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [28]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [29]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [30]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [32]:
np.min(arr), np.max(arr)

(0, 9)

In [34]:
arr.min(), arr.max()

(0, 9)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr.argmin(), arr.argmax()

(0, 9)

In [38]:
np.random.shuffle(arr)

In [39]:
arr

array([1, 7, 4, 3, 2, 9, 5, 8, 6, 0])

In [40]:
arr.argmin(), arr.argmax()

(9, 5)

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [41]:
arr.sum()

45

In [42]:
arr.mean()

4.5

In [44]:
arr.std()

2.8722813232690143

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [45]:
arr.shape

(10,)

In [46]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
M.sum()

45

In [48]:
M.sum(axis=0)

array([12, 15, 18])

In [49]:
M.sum(axis=1)

array([ 6, 15, 24])

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='axis_logic.png' width=400/>

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

**Actividad 1:**

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso =   [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el imc para cada jugador.

> b) Indicar en qué índice se encuentra el imc más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los imc resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menor imc al que tiene mayor imc.